# Generated by Django 3.1.2 on 2020-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('s_class', models.IntegerField(help_text='Enter which class you are in ( ex:10 )')),
                ('lang', models.CharField(blank=True, choices=[('H', 'Hindi'), ('E', 'English'), ('T', 'Telugu')], default='E', help_text='Enter the language', max_length=1)),
            ],
        ),
    ]
