# Generated by Django 3.1.2 on 2020-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='lang',
            field=models.CharField(blank=True, choices=[('H', 'Hindi'), ('E', 'English'), ('T', 'Telugu')], default='E', help_text='Enter the language', max_length=1, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='s_class',
            field=models.IntegerField(help_text='Enter which class you are in ( ex:10 )', verbose_name='Class'),
        ),
    ]
