# Generated by Django 3.1.2 on 2020-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20201030_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach_prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('teach_class', models.IntegerField(help_text='Enter upto which class you can teach ( ex:10 )', verbose_name='Teach Upto')),
                ('lang', models.CharField(blank=True, choices=[('H', 'Hindi'), ('E', 'English'), ('T', 'Telugu')], default='E', help_text='Enter the language', max_length=1, verbose_name='Language')),
                ('Qualify', models.CharField(help_text='Enter your highest qualification', max_length=50, verbose_name='Qualification')),
                ('Subj', models.CharField(max_length=20, null=True, verbose_name='Subject')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('Email', models.EmailField(default='null', max_length=200)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Contact')),
            ],
        ),
    ]
