# Generated by Django 3.1.2 on 2020-10-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_teach_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_profile',
        ),
    ]
